### ISSUE TITLE
Project opening issue ?

### ISSUE THREAD

**Issue by Immudelki** [Adsolution/Ray1Map#10]
Pretty sure I've done everything as written (tried twice), but upon opening the Unity project, I will get a:
Assets\Scripts\Helpers\GAX\GAX_XMWriter.cs(246,17): error CS0117: 'XM_Pattern' does not contain a definition for 'NumChannels'

![image](https://github.com/BinarySerializer/Ray1Map/assets/21196587/a70eba79-991f-4b0d-9a32-d7f537d94cec)

Am I missing something or is it a genuine bug ?
I followed that procedure since I downloaded the repo as a zip:
_"download the sub-module repos [...] and place them in the specified folders:"_
All downloaded and placed in the right folders.

(I'm a regular unity user btw)
Tested with 2022.3.7

Thanks for your help

**Comment by RayCarrot** [comment]
Hi! Ray1Map was using an older version of the `BinarySerializer.Audio` library, while you were downloading the latest version. I updated Ray1Map now to use the latest version, so if you download it again it should work now 🙂

**Comment by Immudelki** [comment]
![image](https://github.com/BinarySerializer/Ray1Map/assets/21196587/f8e22af6-9e0e-44da-ac83-c21c0896df01)
Aye aye. Now I'm getting lost GUID's on the assembly
Sorry for that mess o-o"

**Comment by RayCarrot** [comment]
Hm, not sure what's causing that. Maybe try re-downloading? If you have a git client, such as GitHub Desktop, installed I would recommend using that to clone the repo instead since that will automatically download all sub-modules.

Edit: Oh also, are you using the same Unity version as mentioned in the readme?

**Comment by Immudelki** [comment]
I guess yeah the issue might come from submodule separate download, which looses GUID since we reimport, i'll go for the git client direction then.
Yup. same unity version ^-^
