### ISSUE TITLE
The requested file Data/Paks/Resources.pak was not found error

### ISSUE THREAD

**Issue by Lilothestitch16** [Adsolution/Ray1Map#11]
I get this error called "The requested file Data/Paks/Resources.pak" especially when I set the location for it. Did I do something wrong?

![Ray1Map Error 1](https://github.com/BinarySerializer/Ray1Map/assets/8963276/2d429376-6d8f-4d61-a4a1-18c1de1c1fd2)
![Ray1Map Error 2](https://github.com/BinarySerializer/Ray1Map/assets/8963276/d36d73f9-7c30-4424-a7b7-f43f18f6164f)

**Comment by RayCarrot** [comment]
You need to set the path to be to the game itself, not the paks sub-folder. So just remove the "Data/Paks" part of your path.

**Comment by Lilothestitch16** [comment]
Ok thank you for your help. I’ll go do that now.
