### ISSUE TITLE
Not loading maps on Firefox

### ISSUE THREAD

**Issue by ShinyRaichu94** [Adsolution/Ray1Map#5]
For some reason, it's stuck on the loading screen while using the online browser version on Firefox, not loading any maps.

**Comment by byvar** [comment]
That's odd. Have you checked if hardware acceleration is enabled in your browser?
If it is, does the tab have focus while it's loading (it tends to pause when it loses focus)?

**Comment by ShinyRaichu94** [comment]
The hardware acceleration is enabled, but I don't know about the focus.

**Comment by ShinyRaichu94** [comment]
Okay, I think it's something to do with WebGL. I test out some other games that runs by this. Most of them works, but some won't load at all.
