### ISSUE TITLE
Enter in Safe Mode in Unity 

### ISSUE THREAD

**Issue by ElZboub** [Adsolution/Ray1Map#6]
For several months now, I can't run Ray1Maps without receiving a message telling me that the project has compilation errors and that I should run in Safe Mode. The problem is that I can't do anything in Safe Mode and if I decide to ignore the error message, I simply can't load the games.

**Comment by RayCarrot** [comment]
Which compilation errors is it showing? Most likely you're missing one or more of the sub-modules as they don't always get included in the repo by default. You can find the links to them and where to place them in the [readme here](https://github.com/Adsolution/Ray1Map#get-started).

**Comment by ElZboub** [comment]
I actually didn't have the sub-modules! I just downloaded them and everything works perfectly! I should have looked at the readme better before declaring an issue. Thanks a lot!

**Comment by RayCarrot** [comment]
No problem, glad it's working now!
