### ISSUE TITLE
Cannot View Rayman PS1 DemoDemo Vol3 Japan Maps

### ISSUE THREAD

**Issue by Dynaroo10** [Adsolution/Ray1Map#7]
Upon attempting to view either map, it comes up with this error message. I have tried in both Firefox and Chrome. All other games seem to be fine.
![Screenshot (4)](https://user-images.githubusercontent.com/71418884/156295598-a32666c1-3b67-4771-911e-cddbd966c703.png)

**Comment by RayCarrot** [comment]
Thanks for reporting it! I had missed that this stopped working after the last update. I've fixed it now!
